listen=YES
listen_ipv6=NO
anonymous_enable=NO
local_enable=YES
write_enable=YES
dirmessage_enable=YES

xferlog_enable=NO
log_ftp_protocol=YES
vsftpd_log_file=/var/log/vsftpd.log

pam_service_name=vsftpd
userlist_enable=YES
userlist_deny=NO
userlist_file=/etc/vsftpd.userlist

chroot_local_user=YES
allow_writeable_chroot=YES
local_root=/var/www/html

seccomp_sandbox=NO
use_sendfile=NO
setproctitle_enable=NO
session_support=NO

pasv_enable=YES
pasv_addr_resolve=YES
secure_chroot_dir=/var/run/vsftpd/empty

local_umask=002
file_open_mode=0664
